### ISSUE TITLE
Product 관련 테스트 케이스 작성

### ISSUE THREAD

**Issue by Ksiyeong** [codestates-seb/seb41_main_007#51]
## Description
- Product와 관련된 Controller 테스트 케이스 작성

## Todo
1. [x] ProductController 테스트 케이스 작성
2. [x] ProductSubController 테스트 케이스 작성
3. [x] MainController 테스트 케이스 작성

## ETC
- 기타 참고사항

**Comment by Ksiyeong** [comment]
Product 관련 Controller 테스트 케이스 작성 완료
